language: php
php:
  - 5.6
  - 7.0

install:
  - composer require --no-interaction satooshi/php-coveralls
  - composer install --no-interaction

script:
  - mkdir -p ./test/logs
  - ./vendor/bin/phpunit -c ./test/phpunit.xml.dist

after_success:
  - travis_retry php ./vendor/bin/coveralls -x ./test/logs/clover.xml

